### ISSUE TITLE
ignoreOneWayPlatformsThisFrame + sloped one way platform = !!!SUPER JUMP!!!

### ISSUE THREAD

**Issue by SharpenedSpoon** [prime31/CharacterController2D#58] opened 2015-07-06 00:01 UTC
I submit this bug in the form of a (low FPS, sorry) gif:

![ignoreonewayplatformsbug](https://cloud.githubusercontent.com/assets/1900836/8514006/1fa0db50-2337-11e5-972e-e5190aa6c143.gif)

Pretty sure I know the issue, and I would submit a pull request but I am unsure as to how you want to approach the solution. In the DemoScene.cs example, when holding "down" on a sloped platform, we do not fall through it, but still get our y-velocity multiplied by 3 - so, if we also hit jump while holding down, since we get a jump y-velocity assigned before the "falling through platforms" y-velocity, then we launch way up into the air!

Entirely possible this is a feature, not a bug :D

**Comment by prime31** [comment] 2015-07-06 00:10
That is DEFINITELY a feature! I vote for leaving it as is. 

Mike


On Jul 5, 2015, at 5:01 PM, Ian Douglas <notifications@github.com> wrote:

I submit this bug in the form of a (low FPS, sorry) gif:



Pretty sure I know the issue, and I would submit a pull request but I am unsure as to how you want to approach the solution. In the DemoScene.cs example, when holding "down" on a sloped platform, we do not fall through it, but still get our y-velocity multiplied by 3 - so, if we also hit jump while holding down, since we get a jump y-velocity assigned before the "falling through platforms" y-velocity, then we launch way up into the air!

Entirely possible this is a feature, not a bug :D

**Comment by Candescence** [comment] 2015-08-21 18:23
At least let us turn if off :p

**Comment by Candescence** [comment] 2015-08-26 18:35
Also, the bug can occur virtually anywhere that isn't a one-way platform. I'm not really sure how to fix it while still allowing the controller to drop down through the platform.

**Comment by tfinck** [comment] 2015-10-12 17:36
A simple fix for this is simply to modify the following. 

```
if (_controller.isGrounded && Input.GetKey (KeyCode.DownArrow)) {
			    //_velocity.y *= 3f;      <-- comment this line out
			    _controller.ignoreOneWayPlatformsThisFrame = true;
		    }
```

**Closed** 2016-10-10 16:16 UTC
